services:
  - type: web
    plan: free
    name: anyproduct
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn producter.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
