# Generated by Django 5.0.6 on 2024-05-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_product_cart_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_cart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
