# Generated by Django 5.0.6 on 2024-05-19 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_remove_product_cart_cart_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_cart',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productapp.shopping_cart'),
            preserve_default=False,
        ),
    ]
