# Generated by Django 5.0.6 on 2024-05-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_product_cart_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_cart',
            name='brand',
            field=models.CharField(default='Wish wonders', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_cart',
            name='weight',
            field=models.IntegerField(default=250),
            preserve_default=False,
        ),
    ]
